#!/usr/bin/perl
## Pombert Lab, IIT, 2018
my $name = 'splitGFF3.pl';
my $version = '0.2';

use strict; use warnings; use Getopt::Long qw(GetOptions);

## Defining options
my $usage = <<"OPTIONS";
NAME		$name
VERSION		$version
SYNOPSIS	Splits the WebApollo GFF3 file and creates a GFF3 (.gff3) and a FASTA (.fsa) file per contig
USAGE		splitGFF3.pl -g file.gff3
OPTIONS:
-g	## GFF3 file generated by WebApollo
OPTIONS
die "$usage\n" unless @ARGV;

my $gff3;
GetOptions('g=s' => \$gff3);

## Parsing GFF3 files
my %contigs; my $fasta = undef;
open IN, "<$gff3";
while (my $line = <IN>){
	chomp $line;
	if($line =~ /^##FASTA/){$fasta = 1;}## Annotations are listed before FASTA sequences in WebApollo GFF3 files
	elsif ($line =~ /^#/){next;}
	elsif ($line =~ /^>(\S+)/){$fasta = $1;} ## Checking for presence of FASTA sequences at the end of WebApollo GFF3 files
	elsif (($line =~ /^(\S+)/) && (!defined $fasta)){
		my $contig = $1;
		push (@{$contigs{$contig}[0]}, $line);
	}
	else {$contigs{$fasta}[1] .= $line;}
}
for my $key (keys %contigs){
	open GFF3, ">$key.gff3";
	if (exists $contigs{$key}[1]){ ## Prints only if FASTA is present in the GFF3 file
		open FASTA, ">$key.fsa";
		print FASTA ">$key\n";
		my @seq = unpack ("(A60)*", $contigs{$key}[1]);
		while (my $tmp = shift@seq){print FASTA "$tmp\n";}
		close FASTA;
	}
	if (exists $contigs{$key}[0]){
		while (my $feature = shift@{$contigs{$key}[0]}){print GFF3 "$feature\n";}
		close GFF3;
	}
}
exit;
